title: "📄 [문서] {제목을 작성해주세요}"
labels:
  - "문서"
body:
  # 안내 문구(마크다운)
  - type: textarea
    id: content
    attributes:
      value: |
        <!-- 
        📚 GitHub Discussions 문서 작성 템플릿
        아래 항목을 참고하여 문서를 작성해주세요. 필요한 부분을 자유롭게 작성하시면 됩니다.
        -->
        
        
        <!--
        📝 기본 개념
        사전 지식 및 기본적인 개념에 대해 작성해주세요
        -->
        
        <--
        🎯 본문
        개발 과정에서 구현한 내용이나 기술적인 세부사항을 작성해주세요.
        -->
        
        <--
        📚 기대효과
        해당 기능을 사용했을 때의 기대효과에 대해서 적어주세요
        예: 사용자 인증 프로세스 개선
        -->
        
        <--
        🔗 관련 자료
        관련된 문서나 외부 링크를 공유해주세요.
        - [링크1](http://example.com)
        - [링크2](http://example.com)
        - #이슈번호
        -->
        
        <--
        🙋‍ 담당자
        - 백엔드: 이름
        - 프로트엔드: 이름
        - 디자인: 이름
        -->
