name: SEJONG-MALSAMI-BE-PR-Build

on:
  pull_request:
    branches:
      - epic/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create application-prod.yml from secret
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_PROD_YML }}" > ./src/main/resources/application-prod.yml

      - name: Create yeopjeon.yml from secret
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.YEOPJEON_YML }}" > ./src/main/resources/yeopjeon.yml

      - name: Create score.yml from secret
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.SCORE_YML }}" > ./src/main/resources/score.yml

      - name: Create exp.yml from secret
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.EXP_YML }}" > ./src/main/resources/exp.yml

      - name: Create admin.yml from secret
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.ADMIN_YML }}" > ./src/main/resources/admin.yml

      - name: Create post-tier.yml from secret
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.POSTTIER_YML }}" > ./src/main/resources/post-tier.yml

      - name: Build with Gradle
        run: ./gradlew clean build -x test -Dspring.profiles.active=prod